function_name:function_terminal
            | function_string
            | function_conversion
            | function_list
            | function_
function_terminal:"输入" 
                | "错误"
                | "警告"
                | "调试"
                | "输出"
function_string:"文本长度" 
            | "文本索引" 
            | "文本拼接" 
            | "文本提取" 
            | "文本分割" 
            | "文本匹配"
            | "文本搜索"
            | "文本替换"
            | "文本过滤"
function_math:"取最大值"
            | "取最小值"
            | "取随机数"
            | "取绝对值"
            | "取相反数"
            | "四舍五入"
            | "向上取整"
            | "向下取整"
            | "指数运算"
            | "对数运算"
            | "公式运算"
function_conversion:"数据类型"
                | "转化整数"
                | "转化小数"
                | "转化文本"
                | "转化真假"
function_list:"列表长度"
            | "列表合并"
            | "列表索引"
            | "列表搜索"
            | "列表排序"
            | "列表插入"
            | "列表过滤"
            | "列表移除"
            | "列表修改"
            | "列表去重"
            | "列表切片"
function_time:"当前时间"
            | "时间差值"
function_file:"文件读取"
            | "文件覆写"
            | "文件追加"
            | "文件大小"
            | "文件信息"
            | "文件存在"
function_path:"路径拼接"
            | "路径索引"
            | "路径解析"