%import common.DIGIT
%import common.HEXDIGIT
%import common.INT
%import common.SIGNED_INT
%import common.DECIMAL
%import common.FLOAT
%import common.SIGNED_FLOAT
%import common.NUMBER
%import common.SIGNED_NUMBER
%import common.ESCAPED_STRING
%import common.LCASE_LETTER
%import common.UCASE_LETTER
%import common.LETTER
%import common.WORD
%import common.CNAME
%import common.WS_INLINE
%import common.WS
%import common.NEWLINE
%import common.SH_COMMENT
%import common.CPP_COMMENT
%import common.C_COMMENT
%import common.SQL_COMMENT
%ignore WS

COMMENT: SH_COMMENT | CPP_COMMENT | C_COMMENT | SQL_COMMENT