%import common.WS
%ignore WS

start: statements
statements: statement+
statement: define_quote
         | define_type
         | define_capacity
         | define_variable
         | define_constant
         | struct_quote
         | struct_class
         | struct_function
         | access_pipe
         | access_object
         | access_option
         | control_loop
         | control_select
         | module_import
         | module_export

define_quote: name
define_type:     "类型" type ":" name "=" data
define_constant: "常量" type ":" name "=" data
define_variable: "变量" type ":" name "=" data
define_capacity: "容量" type ":" name "=" data

struct_quote: name "(" arguments ")"
struct_class: "模型" type ":" name "(" params ")" "{" statements "}"
struct_function:  "函数" type ":" name "(" params ")" "{" statements "}"

control_loop:   "循环" "(" name ")" "{" statements "}"
control_select: "如果" "(" name ")" "{" statements "}" "或者" "(" name ")" "{" statements "}" 

access_option: value ("?" name)+
access_object: value ("." name)+
access_pipe: value ("|" struct_quote)+

module_import: "导入" name
module_export: "导出" name

data: value | struct_quote | define_quote
argument: value | struct_quote | define_quote
arguments: (argument ("," argument)*)?
param: type ":" name
params: (param ("," param)*)?
value: string | number | bool | list | object

// 常量

  // 数字类型
  number: real | percentage | permille | permyriad

  sign: /[+-]/
  natural: /[0-9]+/
  integer: sign? natural
  decimal: sign? natural "." natural
  fraction: integer "/" natural
  real: integer | decimal | fraction

  percentage: real "%"
  permille: real "‰"
  permyriad: real "‱"

  // 文本类型
  string: /"[^"]*"/ | /'[^']*'/

  // 状态类型
  bool: "真" | "假"

// 变量

  type: name
  name: /[a-zA-Z_\u4e00-\u9fff\u3400-\u4DBF][a-zA-Z0-9_\u4e00-\u9fff\u3400-\u4DBF]*/

// 容量

  // 列表类型
  list: "[" (value ("," value)*)? "]"
  object: "{" (pair ("," pair)*)? "}"
  pair: key ":" value
  key: name | string | integer