%import common.WS
%ignore WS

start: statement+
statement: value
         | define_type
         | define_capacity
         | define_function
         | define_variable
         | define_constant
         | define_property
         | define_structure
         | access_pipe
         | access_object
         | access_optional
         | control_loop
         | control_select

define_type:     "类型" type ":" name "=" value
define_constant: "常量" type ":" name "=" value
define_variable: "变量" type ":" name "=" value
define_capacity: "容量" type ":" name "=" value
define_property: "属性" type ":" name "=" value

define_function:  "函数" type ":" name "(" params ")" "{" start "}"
define_structure: "结构" type ":" name "(" params ")" "{" start "}"

control_loop:   "循环" "(" name ")" "{" start "}"
control_select: "如果" "(" name ")" "{" start "}" 

access_pipe:     value ("|" function)+
access_object:   value ("." name)+
access_optional: value ("?" name)+

arguments: (value ("," value)*)?
params: (type ":" name ("," type ":" name)*)?
value: string | number | bool | list | object | name | function
function:   name "(" arguments ")"

// 常量

  // 数字类型
  number: real | percentage | permille | permyriad

  sign: /[+-]/
  natural: /[0-9]+/
  integer: sign? natural
  decimal: sign? natural "." natural
  fraction: integer "/" natural
  real: integer | decimal | fraction

  percentage: real "%"
  permille: real "‰"
  permyriad: real "‱"

  // 文本类型
  string: /"[^"]*"/ | /'[^']*'/

  // 状态类型
  bool: "真" | "假"

// 变量

  type: name
  name: /[a-zA-Z0-9_\u4e00-\u9fff\u3400-\u4DBF]+/

// 容量

  // 列表类型
  list: "[" (value ("," value)*)? "]"
  object: "{" (pair ("," pair)*)? "}"
  pair: key ":" value
  key: name | string | integer